In [2]:
import pandas as pd

df = pd.read_csv('moviesTMBD.csv')

df

,Unnamed: 0,id,title,popularity,adult,original_language,overview,release_date,vote_average,vote_count
0,0,1007757,Swapped,327.5134,False,en,"A small woodland creature and a majestic bird,...",2026-05-01,8.987,1320
1,1,278,The Shawshank Redemption,65.3308,False,en,Imprisoned in the 1940s for the double murder ...,1994-09-23,8.721,30387
2,2,238,The Godfather,47.2346,False,en,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,8.686,22929
3,3,687163,Project Hail Mary,422.0199,False,en,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,8.621,3950
4,4,240,The Godfather Part II,27.6763,False,en,In the continuing saga of the Corleone crime f...,1974-12-20,8.571,13901
...,...,...,...,...,...,...,...,...,...,...
9975,9975,399173,The Assignment,2.1132,False,en,Ace assassin Frank Kitchen is double crossed b...,2016-06-08,5.538,560
9976,9976,613377,30 Days Max,1.2237,False,fr,Rayane is a scared and clumsy young cop who is...,2020-10-14,5.500,407
9977,9977,8859,"Dude, Where's My Car?",2.8157,False,en,Two stoners wake up after a night of partying ...,2000-12-15,5.538,2080
9978,9978,313943,Revolt,1.4022,False,en,The story of humankind's last stand against a ...,2017-07-01,5.537,393
9979,9979,277355,Everly,2.0746,False,en,"After she betrays a powerful mob boss, a woman...",2015-02-26,5.536,584

In [5]:
df[df['vote_count'] > 1000]

,Unnamed: 0,id,title,popularity,adult,original_language,overview,release_date,vote_average,vote_count
0,0,1007757,Swapped,327.5134,False,en,"A small woodland creature and a majestic bird,...",2026-05-01,8.987,1320
1,1,278,The Shawshank Redemption,65.3308,False,en,Imprisoned in the 1940s for the double murder ...,1994-09-23,8.721,30387
2,2,238,The Godfather,47.2346,False,en,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,8.686,22929
3,3,687163,Project Hail Mary,422.0199,False,en,Science teacher Ryland Grace wakes up on a spa...,2026-03-15,8.621,3950
4,4,240,The Godfather Part II,27.6763,False,en,In the continuing saga of the Corleone crime f...,1974-12-20,8.571,13901
...,...,...,...,...,...,...,...,...,...,...
9967,9967,38322,"Big Mommas: Like Father, Like Son",3.3429,False,en,FBI agent Malcolm Turner and his 17-year-old s...,2011-02-16,5.547,1301
9970,9970,277685,Unfriended,3.4109,False,en,"While video chatting one night, six high schoo...",2014-06-18,5.545,3526
9971,9971,10923,Agent Cody Banks,2.6469,False,en,Recruited by the U.S. government to be a speci...,2003-03-14,5.545,1163
9972,9972,9904,The Wild,4.8729,False,en,An adolescent lion is accidentally shipped fro...,2006-04-06,5.500,1129
9977,9977,8859,"Dude, Where's My Car?",2.8157,False,en,Two stoners wake up after a night of partying ...,2000-12-15,5.538,2080

In [8]:
df[df['original_language'] == 'ja']

,Unnamed: 0,id,title,popularity,adult,original_language,overview,release_date,vote_average,vote_count
8,8,129,Spirited Away,32.2851,False,ja,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,8.534,18302
16,16,372058,Your Name.,28.9733,False,ja,High schoolers Mitsuha and Taki are complete s...,2016-08-26,8.479,12547
22,22,346,Seven Samurai,13.9369,False,ja,A samurai answers a village's request for prot...,1954-04-26,8.452,4226
23,23,12477,Grave of the Fireflies,0.0128,False,ja,"In the final months of World War II, 14-year-o...",1988-04-16,8.441,6509
27,27,14537,Harakiri,9.1065,False,ja,Down-on-his-luck veteran Tsugumo Hanshirō ente...,1962-09-15,8.400,1206
...,...,...,...,...,...,...,...,...,...,...
8701,8701,1679,Godzilla Raids Again,2.3828,False,ja,Two fishing scout pilots make a horrifying dis...,1955-04-24,5.979,330
8801,8801,59429,Paranormal Activity: Tokyo Night,1.6746,False,ja,"Koichi takes care of his sister, who has recen...",2010-11-20,6.000,465
9149,9149,485942,Batman Ninja,4.1887,False,ja,"Batman, along with many of his allies and adve...",2018-03-24,5.858,1068
9368,9368,9669,Ring 2,3.4635,False,ja,While investigating the horrifying death of he...,1999-01-23,5.800,458
9413,9413,39106,Dragon Ball Z: Bio-Broly,3.6402,False,ja,"Jaga Bada, Mr. Satan's old sparring partner, h...",1994-07-09,5.780,564